# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/i2cio.xdc

# Block Designs: bd/design_i2c/design_i2c.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_i2c || ORIG_REF_NAME==design_i2c} -quiet] -quiet

# IP: bd/design_i2c/ip/design_i2c_microblaze_0_1/design_i2c_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_i2c_microblaze_0_1 || ORIG_REF_NAME==design_i2c_microblaze_0_1} -quiet] -quiet

# IP: bd/design_i2c/ip/design_i2c_dlmb_v10_1/design_i2c_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_i2c_dlmb_v10_1 || ORIG_REF_NAME==design_i2c_dlmb_v10_1} -quiet] -quiet

# IP: bd/design_i2c/ip/design_i2c_ilmb_v10_1/design_i2c_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_i2c_ilmb_v10_1 || ORIG_REF_NAME==design_i2c_ilmb_v10_1} -quiet] -quiet

# IP: bd/design_i2c/ip/design_i2c_dlmb_bram_if_cntlr_1/design_i2c_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_i2c_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==design_i2c_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/design_i2c/ip/design_i2c_ilmb_bram_if_cntlr_1/design_i2c_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_i2c_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==design_i2c_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/design_i2c/ip/design_i2c_lmb_bram_1/design_i2c_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_i2c_lmb_bram_1 || ORIG_REF_NAME==design_i2c_lmb_bram_1} -quiet] -quiet

# IP: bd/design_i2c/ip/design_i2c_xbar_1/design_i2c_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_i2c_xbar_1 || ORIG_REF_NAME==design_i2c_xbar_1} -quiet] -quiet

# IP: bd/design_i2c/ip/design_i2c_microblaze_0_axi_periph_1/design_i2c_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_i2c_microblaze_0_axi_periph_1 || ORIG_REF_NAME==design_i2c_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/design_i2c/ip/design_i2c_microblaze_0_axi_intc_1/design_i2c_microblaze_0_axi_intc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_i2c_microblaze_0_axi_intc_1 || ORIG_REF_NAME==design_i2c_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/design_i2c/ip/design_i2c_microblaze_0_xlconcat_1/design_i2c_microblaze_0_xlconcat_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_i2c_microblaze_0_xlconcat_1 || ORIG_REF_NAME==design_i2c_microblaze_0_xlconcat_1} -quiet] -quiet

# IP: bd/design_i2c/ip/design_i2c_mdm_1_1/design_i2c_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_i2c_mdm_1_1 || ORIG_REF_NAME==design_i2c_mdm_1_1} -quiet] -quiet

# IP: bd/design_i2c/ip/design_i2c_clk_wiz_1_1/design_i2c_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_i2c_clk_wiz_1_1 || ORIG_REF_NAME==design_i2c_clk_wiz_1_1} -quiet] -quiet

# IP: bd/design_i2c/ip/design_i2c_rst_clk_wiz_1_100M_1/design_i2c_rst_clk_wiz_1_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_i2c_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==design_i2c_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/design_i2c/ip/design_i2c_axi_uartlite_0_0/design_i2c_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_i2c_axi_uartlite_0_0 || ORIG_REF_NAME==design_i2c_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_i2c/ip/design_i2c_axi_iic_0_2/design_i2c_axi_iic_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_i2c_axi_iic_0_2 || ORIG_REF_NAME==design_i2c_axi_iic_0_2} -quiet] -quiet

# XDC: c:/Parvathy/project_i2c_microblaze/project_i2c_microblaze.gen/sources_1/bd/design_i2c/design_i2c_ooc.xdc
