# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Parvathy/project_MB_spec/project_MB_spec.srcs/sources_1/bd/design_mb/ip/design_mb_axi_bram_ctrl_0_bram_0/design_mb_axi_bram_ctrl_0_bram_0.xci
# IP: The module: 'design_mb_axi_bram_ctrl_0_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Parvathy/project_MB_spec/project_MB_spec.gen/sources_1/bd/design_mb/ip/design_mb_axi_bram_ctrl_0_bram_0/design_mb_axi_bram_ctrl_0_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_mb_axi_bram_ctrl_0_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Parvathy/project_MB_spec/project_MB_spec.srcs/sources_1/bd/design_mb/ip/design_mb_axi_bram_ctrl_0_bram_0/design_mb_axi_bram_ctrl_0_bram_0.xci
# IP: The module: 'design_mb_axi_bram_ctrl_0_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Parvathy/project_MB_spec/project_MB_spec.gen/sources_1/bd/design_mb/ip/design_mb_axi_bram_ctrl_0_bram_0/design_mb_axi_bram_ctrl_0_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_mb_axi_bram_ctrl_0_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
