# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Parvathy/project_MB_spec/project_MB_spec.srcs/sources_1/bd/design_mb/ip/design_mb_clk_wiz_1_1/design_mb_clk_wiz_1_1.xci
# IP: The module: 'design_mb_clk_wiz_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Parvathy/project_MB_spec/project_MB_spec.gen/sources_1/bd/design_mb/ip/design_mb_clk_wiz_1_1/design_mb_clk_wiz_1_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_mb_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Parvathy/project_MB_spec/project_MB_spec.gen/sources_1/bd/design_mb/ip/design_mb_clk_wiz_1_1/design_mb_clk_wiz_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_mb_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Parvathy/project_MB_spec/project_MB_spec.gen/sources_1/bd/design_mb/ip/design_mb_clk_wiz_1_1/design_mb_clk_wiz_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_mb_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Parvathy/project_MB_spec/project_MB_spec.srcs/sources_1/bd/design_mb/ip/design_mb_clk_wiz_1_1/design_mb_clk_wiz_1_1.xci
# IP: The module: 'design_mb_clk_wiz_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Parvathy/project_MB_spec/project_MB_spec.gen/sources_1/bd/design_mb/ip/design_mb_clk_wiz_1_1/design_mb_clk_wiz_1_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_mb_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Parvathy/project_MB_spec/project_MB_spec.gen/sources_1/bd/design_mb/ip/design_mb_clk_wiz_1_1/design_mb_clk_wiz_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_mb_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Parvathy/project_MB_spec/project_MB_spec.gen/sources_1/bd/design_mb/ip/design_mb_clk_wiz_1_1/design_mb_clk_wiz_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_mb_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
