# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Parvathy/project_i2c_microblaze/project_i2c_microblaze.srcs/sources_1/bd/design_i2c/ip/design_i2c_xbar_1/design_i2c_xbar_1.xci
# IP: The module: 'design_i2c_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Parvathy/project_i2c_microblaze/project_i2c_microblaze.gen/sources_1/bd/design_i2c/ip/design_i2c_xbar_1/design_i2c_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_i2c_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Parvathy/project_i2c_microblaze/project_i2c_microblaze.srcs/sources_1/bd/design_i2c/ip/design_i2c_xbar_1/design_i2c_xbar_1.xci
# IP: The module: 'design_i2c_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Parvathy/project_i2c_microblaze/project_i2c_microblaze.gen/sources_1/bd/design_i2c/ip/design_i2c_xbar_1/design_i2c_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_i2c_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
