# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/uart1.xdc

# Block Designs: bd/design_mb/design_mb.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb || ORIG_REF_NAME==design_mb} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_xbar_0/design_mb_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb_xbar_0 || ORIG_REF_NAME==design_mb_xbar_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_microblaze_0_axi_periph_0/design_mb_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_mb_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_microblaze_0_axi_intc_0/design_mb_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_mb_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_microblaze_0_xlconcat_0/design_mb_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb_microblaze_0_xlconcat_0 || ORIG_REF_NAME==design_mb_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_uartlite_0_0/design_mb_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb_axi_uartlite_0_0 || ORIG_REF_NAME==design_mb_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_bram_ctrl_0_0/design_mb_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_mb_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_bram_ctrl_0_bram_0/design_mb_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==design_mb_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_quad_spi_0_1/design_mb_axi_quad_spi_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb_axi_quad_spi_0_1 || ORIG_REF_NAME==design_mb_axi_quad_spi_0_1} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_iic_0_0/design_mb_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb_axi_iic_0_0 || ORIG_REF_NAME==design_mb_axi_iic_0_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_gpio_0_2/design_mb_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb_axi_gpio_0_2 || ORIG_REF_NAME==design_mb_axi_gpio_0_2} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_gpio_1_2/design_mb_axi_gpio_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb_axi_gpio_1_2 || ORIG_REF_NAME==design_mb_axi_gpio_1_2} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_uartlite_1_1/design_mb_axi_uartlite_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb_axi_uartlite_1_1 || ORIG_REF_NAME==design_mb_axi_uartlite_1_1} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_microblaze_0_0/design_mb_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb_microblaze_0_0 || ORIG_REF_NAME==design_mb_microblaze_0_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_dlmb_v10_1/design_mb_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb_dlmb_v10_1 || ORIG_REF_NAME==design_mb_dlmb_v10_1} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_ilmb_v10_1/design_mb_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb_ilmb_v10_1 || ORIG_REF_NAME==design_mb_ilmb_v10_1} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_dlmb_bram_if_cntlr_1/design_mb_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==design_mb_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_ilmb_bram_if_cntlr_1/design_mb_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==design_mb_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_lmb_bram_1/design_mb_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb_lmb_bram_1 || ORIG_REF_NAME==design_mb_lmb_bram_1} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_mdm_1_1/design_mb_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb_mdm_1_1 || ORIG_REF_NAME==design_mb_mdm_1_1} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_clk_wiz_1_1/design_mb_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb_clk_wiz_1_1 || ORIG_REF_NAME==design_mb_clk_wiz_1_1} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_rst_clk_wiz_1_100M_1/design_mb_rst_clk_wiz_1_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==design_mb_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_auto_pc_0/design_mb_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mb_auto_pc_0 || ORIG_REF_NAME==design_mb_auto_pc_0} -quiet] -quiet

# XDC: c:/Parvathy/project_MB_spec/project_MB_spec.gen/sources_1/bd/design_mb/design_mb_ooc.xdc
