# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1_mico_cust/design_1_mico_cust.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mico_cust || ORIG_REF_NAME==design_1_mico_cust} -quiet] -quiet

# IP: bd/design_1_mico_cust/ip/design_1_mico_cust_microblaze_0_0/design_1_mico_cust_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mico_cust_microblaze_0_0 || ORIG_REF_NAME==design_1_mico_cust_microblaze_0_0} -quiet] -quiet

# IP: bd/design_1_mico_cust/ip/design_1_mico_cust_dlmb_v10_0/design_1_mico_cust_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mico_cust_dlmb_v10_0 || ORIG_REF_NAME==design_1_mico_cust_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_1_mico_cust/ip/design_1_mico_cust_ilmb_v10_0/design_1_mico_cust_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mico_cust_ilmb_v10_0 || ORIG_REF_NAME==design_1_mico_cust_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_1_mico_cust/ip/design_1_mico_cust_dlmb_bram_if_cntlr_0/design_1_mico_cust_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mico_cust_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_mico_cust_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_1_mico_cust/ip/design_1_mico_cust_ilmb_bram_if_cntlr_0/design_1_mico_cust_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mico_cust_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_mico_cust_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_1_mico_cust/ip/design_1_mico_cust_lmb_bram_0/design_1_mico_cust_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mico_cust_lmb_bram_0 || ORIG_REF_NAME==design_1_mico_cust_lmb_bram_0} -quiet] -quiet

# IP: bd/design_1_mico_cust/ip/design_1_mico_cust_xbar_0/design_1_mico_cust_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mico_cust_xbar_0 || ORIG_REF_NAME==design_1_mico_cust_xbar_0} -quiet] -quiet

# IP: bd/design_1_mico_cust/ip/design_1_mico_cust_microblaze_0_axi_periph_0/design_1_mico_cust_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mico_cust_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_1_mico_cust_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1_mico_cust/ip/design_1_mico_cust_microblaze_0_axi_intc_0/design_1_mico_cust_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mico_cust_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_1_mico_cust_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/design_1_mico_cust/ip/design_1_mico_cust_microblaze_0_xlconcat_0/design_1_mico_cust_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mico_cust_microblaze_0_xlconcat_0 || ORIG_REF_NAME==design_1_mico_cust_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/design_1_mico_cust/ip/design_1_mico_cust_mdm_1_0/design_1_mico_cust_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mico_cust_mdm_1_0 || ORIG_REF_NAME==design_1_mico_cust_mdm_1_0} -quiet] -quiet

# IP: bd/design_1_mico_cust/ip/design_1_mico_cust_clk_wiz_1_0/design_1_mico_cust_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mico_cust_clk_wiz_1_0 || ORIG_REF_NAME==design_1_mico_cust_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_1_mico_cust/ip/design_1_mico_cust_rst_clk_wiz_1_100M_0/design_1_mico_cust_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mico_cust_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_1_mico_cust_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_1_mico_cust/ip/design_1_mico_cust_axi_quad_spi_0_0/design_1_mico_cust_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mico_cust_axi_quad_spi_0_0 || ORIG_REF_NAME==design_1_mico_cust_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/design_1_mico_cust/ip/design_1_mico_cust_axi_uartlite_0_0/design_1_mico_cust_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mico_cust_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_mico_cust_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_1_mico_cust/ip/design_1_mico_cust_axi_gpio_0_0/design_1_mico_cust_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mico_cust_axi_gpio_0_0 || ORIG_REF_NAME==design_1_mico_cust_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1_mico_cust/ip/design_1_mico_cust_axi_gpio_1_0/design_1_mico_cust_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mico_cust_axi_gpio_1_0 || ORIG_REF_NAME==design_1_mico_cust_axi_gpio_1_0} -quiet] -quiet

# XDC: /home/arjun/Vivado_PROJECTS/project_1_MICROB_CUSTOM_BOOT/project_1_MICROB_CUSTOM_BOOT.gen/sources_1/bd/design_1_mico_cust/design_1_mico_cust_ooc.xdc
